services:

  - type: web
    name: fraudwatch-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: fraudwatch-ml
    env: python
    plan: free
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: web
    name: fraudwatch-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 3000
